import { useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, Loader2, Sparkles } from "lucide-react";
import ReactMarkdown from "react-markdown";
import { StackedLogo } from "@/components/StackedLogo";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

const ANALYSIS_OPTIONS = [
  { id: "strategy", label: "Strategy" },
  { id: "competition", label: "Competition" },
  { id: "negative_media", label: "Negative media" },
  { id: "regulatory", label: "Regulatory" },
  { id: "compliance", label: "Compliance" },
  { id: "financial", label: "Financial" },
  { id: "risk", label: "Risk report" },
];

export default function AIAnalysisTry() {
  const [company, setCompany] = useState("");
  const [website, setWebsite] = useState("");
  const [context, setContext] = useState("");
  const [selected, setSelected] = useState<string[]>(ANALYSIS_OPTIONS.map((o) => o.id));
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<string | null>(null);

  const toggle = (id: string) =>
    setSelected((s) => (s.includes(id) ? s.filter((x) => x !== id) : [...s, id]));

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!company.trim()) {
      toast.error("Please enter a company name.");
      return;
    }
    if (selected.length === 0) {
      toast.error("Select at least one analysis.");
      return;
    }
    setLoading(true);
    setResult(null);
    try {
      const { data, error } = await supabase.functions.invoke("analyze-company", {
        body: { company: company.trim(), website: website.trim(), context: context.trim(), analyses: selected },
      });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);
      setResult(data?.content ?? "");
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Analysis failed. Please try again.";
      toast.error(msg);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Nav */}
      <nav className="sticky top-0 z-50 w-full bg-background border-b border-border px-6">
        <div className="mx-auto flex h-[56px] max-w-[1200px] items-center justify-between">
          <Link to="/" className="flex items-center gap-2 -ml-0.5">
            <StackedLogo size={16} />
            <span className="text-[14px] font-bold text-foreground tracking-[0.08em] uppercase">DcernX</span>
          </Link>
          <Link
            to="/ai-analysis"
            className="inline-flex items-center gap-1.5 text-[13px] text-foreground/70 hover:text-foreground transition-colors"
          >
            <ArrowLeft className="h-3.5 w-3.5" />
            Back to overview
          </Link>
        </div>
      </nav>

      <main className="px-6 pt-14 pb-24">
        <div className="mx-auto max-w-[1200px] grid lg:grid-cols-[420px_1fr] gap-10">
          {/* Form */}
          <aside className="lg:sticky lg:top-[80px] self-start">
            <p className="text-[12px] uppercase tracking-[0.18em] text-muted-foreground mb-4">
              Live primary analysis
            </p>
            <h1 className="text-[28px] font-[500] tracking-[-0.025em] leading-[1.15] text-foreground">
              Run a free analysis on any company.
            </h1>
            <p className="mt-4 text-[14px] text-muted-foreground leading-[1.6]">
              The output is generated by DcernX's analysis agent. Results are illustrative — not investment advice.
            </p>

            <form onSubmit={handleSubmit} className="mt-8 space-y-5">
              <div>
                <label className="block text-[12px] uppercase tracking-[0.12em] text-muted-foreground mb-2">
                  Company name
                </label>
                <input
                  value={company}
                  onChange={(e) => setCompany(e.target.value)}
                  placeholder="e.g. Northwind Robotics"
                  className="w-full h-10 px-3 bg-background border border-border text-[14px] text-foreground placeholder:text-muted-foreground focus:outline-none focus:border-foreground/60 transition-colors"
                />
              </div>
              <div>
                <label className="block text-[12px] uppercase tracking-[0.12em] text-muted-foreground mb-2">
                  Website <span className="lowercase tracking-normal text-muted-foreground/70">(optional)</span>
                </label>
                <input
                  value={website}
                  onChange={(e) => setWebsite(e.target.value)}
                  placeholder="northwindrobotics.com"
                  className="w-full h-10 px-3 bg-background border border-border text-[14px] text-foreground placeholder:text-muted-foreground focus:outline-none focus:border-foreground/60 transition-colors"
                />
              </div>
              <div>
                <label className="block text-[12px] uppercase tracking-[0.12em] text-muted-foreground mb-2">
                  Context <span className="lowercase tracking-normal text-muted-foreground/70">(optional)</span>
                </label>
                <textarea
                  value={context}
                  onChange={(e) => setContext(e.target.value)}
                  rows={4}
                  placeholder="Stage, sector, geography, what your team already knows..."
                  className="w-full px-3 py-2 bg-background border border-border text-[14px] text-foreground placeholder:text-muted-foreground focus:outline-none focus:border-foreground/60 transition-colors resize-y"
                />
              </div>

              <div>
                <label className="block text-[12px] uppercase tracking-[0.12em] text-muted-foreground mb-3">
                  Analyses to run
                </label>
                <div className="flex flex-wrap gap-2">
                  {ANALYSIS_OPTIONS.map((opt) => {
                    const active = selected.includes(opt.id);
                    return (
                      <button
                        type="button"
                        key={opt.id}
                        onClick={() => toggle(opt.id)}
                        className={`h-7 px-3 text-[12px] border transition-colors ${
                          active
                            ? "bg-foreground text-background border-foreground"
                            : "border-border text-muted-foreground hover:text-foreground hover:border-foreground/50"
                        }`}
                      >
                        {opt.label}
                      </button>
                    );
                  })}
                </div>
              </div>

              <button
                type="submit"
                disabled={loading}
                className="group w-full inline-flex items-center justify-center gap-2 px-6 py-3 text-[14px] font-medium bg-foreground text-background hover:bg-foreground/90 transition-colors disabled:opacity-60 disabled:cursor-not-allowed"
              >
                {loading ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin" />
                    Analysing…
                  </>
                ) : (
                  <>
                    <Sparkles className="h-4 w-4" />
                    Run analysis
                  </>
                )}
              </button>
              <p className="text-[11.5px] text-muted-foreground/80 leading-[1.5]">
                Free for evaluation. Subject to fair-use limits. Do not submit confidential third-party material.
              </p>
            </form>
          </aside>

          {/* Result */}
          <section className="min-w-0">
            {!result && !loading && (
              <div className="border border-dashed border-border p-10 lg:p-14 text-center">
                <Sparkles className="h-5 w-5 text-foreground/60 mx-auto" strokeWidth={1.5} />
                <h2 className="mt-5 text-[18px] font-medium text-foreground">Your analysis will appear here.</h2>
                <p className="mt-3 text-[13.5px] text-muted-foreground max-w-[440px] mx-auto leading-[1.6]">
                  Enter a company on the left and the agent will return a structured brief across the selected dimensions.
                </p>
              </div>
            )}

            {loading && (
              <div className="border border-border p-10 lg:p-14 text-center">
                <Loader2 className="h-5 w-5 text-foreground/70 mx-auto animate-spin" />
                <h2 className="mt-5 text-[18px] font-medium text-foreground">Running primary analysis…</h2>
                <p className="mt-3 text-[13.5px] text-muted-foreground max-w-[440px] mx-auto leading-[1.6]">
                  Synthesising {selected.length} {selected.length === 1 ? "section" : "sections"} for {company || "the target"}. Typically 10-30 seconds.
                </p>
              </div>
            )}

            {result && (
              <article className="border border-border p-8 lg:p-12">
                <div className="flex items-center justify-between mb-6 pb-6 border-b border-border">
                  <div>
                    <p className="text-[12px] uppercase tracking-[0.15em] text-muted-foreground">Primary analysis</p>
                    <h2 className="mt-1 text-[22px] font-medium text-foreground tracking-[-0.01em]">{company}</h2>
                  </div>
                  <button
                    onClick={() => {
                      setResult(null);
                    }}
                    className="text-[12px] text-muted-foreground hover:text-foreground transition-colors"
                  >
                    Clear
                  </button>
                </div>
                <div className="prose prose-sm max-w-none text-foreground/85
                  prose-headings:text-foreground prose-headings:font-medium prose-headings:tracking-[-0.01em]
                  prose-h3:text-[16px] prose-h3:mt-8 prose-h3:mb-3 prose-h3:pb-2 prose-h3:border-b prose-h3:border-border
                  prose-p:text-[14px] prose-p:leading-[1.7]
                  prose-li:text-[14px] prose-li:leading-[1.7]
                  prose-strong:text-foreground
                  prose-ul:my-3 prose-ol:my-3
                  dark:prose-invert">
                  <ReactMarkdown>{result}</ReactMarkdown>
                </div>
              </article>
            )}
          </section>
        </div>
      </main>
    </div>
  );
}
